
master:
  replicaCount: 1
coordinating:
  replicaCount: 1
data:
  replicaCount: 1
ingest:
  replicaCount: 1
service:
  type: LoadBalancer
  ports:
    restAPI: 80
    transport: 9300
sysctlImage:
  enabled: true
